from enum import Enum


class RetrievalMode(str, Enum):
    RESOLVE_ATTRIBUTES = "RESOLVE_ATTRIBUTES"
    DONT_RESOLVE_ATTRIBUTES = "DONT_RESOLVE_ATTRIBUTES"
    RESOLVE_OCCURRENCES = "RESOLVE_OCCURRENCES"
    DONT_RESOLVE_OCCURRENCES = "DONT_RESOLVE_OCCURRENCES"
    INLINE_RESOURCE_DATA = "INLINE_RESOURCE_DATA"
    DONT_INLINE_RESOURCE_DATA = "DONT_INLINE_RESOURCE_DATA"

    def __str__(self):
        return self.name
